[package]
name = "blob"
version = "0.1.0"
authors = ["glassonion1 <taisuke.fujita@layerx.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
azure_core = { version = "0.1", git = "https://github.com/Azure/azure-sdk-for-rust.git" }
azure_storage = { version = "0.1", git = "https://github.com/Azure/azure-sdk-for-rust.git", default-features = false, features = ["blob"] }